export NODE_ENV='production'
export APP_NAME='agreement-screen'
export APP_HOST='0.0.0.0'
export APP_PORT=8090
export APP_HTTPS=false
export DB_HEALTHCHECK=15
export ENABLE_CONNECT_DB_SFF='Y'
export ENABLE_CONNECT_DB_SFF_PREPAID='Y'
export ENABLE_CONNECT_DB_CTM='Y'
export ENABLE_CONNECT_MONGO_DB='Y'
export DB_SFF_IP_PORT='172.16.252.26:1521'
export DB_SFF_NAME='SFFDB'
export DB_SFF_USER_NAME='ctmusr'
export DB_SFF_PWD=''
export DB_SFF_POOL_MIN='0'
export DB_SFF_POOL_MAX='10'
export DB_SFF_PREPAID_IP_PORT='172.16.252.53:1521'
export DB_SFF_PREPAID_NAME='OTCDB'
export DB_SFF_PREPAID_USER_NAME='ctmusr'
export DB_SFF_PREPAID_PWD=''
export DB_SFF_PREPAID_POOL_MIN='0'
export DB_SFF_PREPAID_POOL_MAX='10'
export DB_CTM_IP_PORT='10.197.59.113'
export DB_CTM_USER_NAME='ctmusr'
export DB_CTM_PWD=''
export DB_CTM_NAME='CTMPROD'
export DB_CTM_SCHEMA_NAME='ctm'
export DB_CTM_POOL_MIN='0'
export DB_CTM_POOL_MAX='10'
export MONGODB_CLIENT_URI='mongodb://phxinvStream:phxinv2019@10.197.73.217:27017,10.197.73.218:27017,10.197.73.220:27017/phx-inv-prod?replicaSet=rs_onlinestore' # MONGOHQ_URL
export MONGODB_USER_NAME='phxinvStream'
export MONGODB_PASSWORD='phxinv2019'
export MONGODB_SSL_FLAG=false
export SFF_SERVICE_IP_PROTOCOL='http'
export SFF_SERVICE_IP='10.252.64.153'
export SFF_SERVICE_PORT='6100'
export SFF_SERVICE_PATH='/SFFWebService/SFFService'
export SFF_SERVICE_WAIT_TIMEOUT='2'
export DIGITAL_COLLECTION_PROTOCOL='https'
export DIGITAL_COLLECTION_IP='10.138.20.234'
export DIGITAL_COLLECTION_PORT='443'
export DIGITAL_COLLECTION_PATH='/PaymentApp/PaymentService'
export DIGITAL_COLLECTION_WAIT_TIMEOUT='2'
export PGZ_SERVICE_IP_PROTOCOL='http'
export PGZ_SERVICE_IP='10.197.42.82'
export PGZ_SERVICE_PORT='9443'
export PGZ_SERVICE_PATH='/Resources/v1/Fulfillment/synchronous/ServiceProvisioning'
export PGZ_SERVICE_WAIT_TIMEOUT='2'
export IM_SERVICE_IP_PROTOCOL='https'
export IM_SERVICE_IP='myimws-tls1.intra.ais'
export IM_SERVICE_PORT=''
export IM_SERVICE_PATH='/prweb/PRRestService/ExternalInt/Services/CreateExternalActivityLogRequest/createActivity'
export IM_SERVICE_WAIT_TIMEOUT='2'
