#!/bin/sh

export PORT=8443
export NODE_ENV=production
export SSL=true

export LOG_ACCESS_PATH=/app/PHX-LOG/logs/access/access.log
export LOG_API_PATH=/app/PHX-LOG/logs/api/api.log
export LOG_ERROR_PATH=/app/PHX-LOG/logs/error/error.log
export LOG_SERVER_PATH=/app/PHX-LOG/logs/server/server.log

#be PHXInvApp
export PHX_HOST_PORT=http://10.197.42.71:8080
export PHX_HOST_PORT_V2=http://10.197.42.71:8081
export PHX_HOST_PORT_V3=http://10.197.42.71:8082

# CTMInvApp
export CTM_HOST_PORT='http://10.197.42.71:8090'
export CTM_HOST_PATH=''

#export SSL=true
export SERVER_KEY='/app/phx-conf/cert/myoffice-portal.intra.ais.key'
export SERVER_CERT='/app/phx-conf/cert/myoffice-portal.intra.ais.cer'

#SAMLIDS
export IDS_CALL_BACK_URL='https://myoffice-portal.intra.ais:8443/login/callback'
export IDS_ENTRY_POINT='https://ids.ais.co.th/samlsso'
export IDS_LOGOUT_CALL_BACK='https://myoffice-portal.intra.ais:8443/logout/callback'
export IDS_ISSUER='PHX-NEWINV'
export IDS_LOGOUT_URL='https://ids.ais.co.th/samlsso'
export IDS_IDENTIFIER_FORMAT='urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified'
export IDS_CERT='MIICNTCCAZ6gAwIBAgIES343gjANBgkqhkiG9w0BAQUFADBVMQswCQYDVQQGEwJVUzELMAkGA1UECAwCQ0ExFjAUBgNVBAcMDU1vdW50YWluIFZpZXcxDTALBgNVBAoMBFdTTzIxEjAQBgNVBAMMCWxvY2FsaG9zdDAeFw0xMDAyMTkwNzAyMjZaFw0zNTAyMTMwNzAyMjZaMFUxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJDQTEWMBQGA1UEBwwNTW91bnRhaW4gVmlldzENMAsGA1UECgwEV1NPMjESMBAGA1UEAwwJbG9jYWxob3N0MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCUp/oV1vWc8/TkQSiAvTousMzOM4asB2iltr2QKozni5aVFu818MpOLZIr8LMnTzWllJvvaA5RAAdpbECb+48FjbBe0hseUdN5HpwvnH/DW8ZccGvk53I6Orq7hLCv1ZHtuOCokghz/ATrhyPq+QktMfXnRS4HrKGJTzxaCcU7OQIDAQABoxIwEDAOBgNVHQ8BAf8EBAMCBPAwDQYJKoZIhvcNAQEFBQADgYEAW5wPR7cr1LAdq+IrR44iQlRG5ITCZXY9hI0PygLP2rHANh+PYfTmxbuOnykNGyhM6FjFLbW2uZHQTY1jMrPprjOrmyK5sjJRO4d1DeGHT/YnIjs9JogRKv4XHECwLtIVdAbIdWHEtVZJyMSktcyysFcvuhPQK8Qc/E/Wq8uHSCo='

# Local Password
export LOCAL_STRATEGY_PASSWORD_FIELD='password'
export LOCAL_STRATEGY_PASSWORD_SAML_SYSTEM='P@ssW0rd'
export LOCAL_STRATEGY_PASSWORD_NAS_MY_OFFICE='P@ssW0rd'
export LOCAL_STRATEGY_PASSWORD_WEB_PRODUCTION_PLAN='P@ssW0rd'

# TOKEN
export JSON_TOKEN_SECRET_MC='jQQ02TbNvNHb+9tkT85bFWlnmS213qKhcmtNSLvDjw=='
